import { StyleSheet } from 'react-native';

export const framePostStyles = StyleSheet.create({
  frameOverlayImageWrap: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    top: 0,
    zIndex: 10,
    justifyContent: 'flex-end',
    backgroundColor: 'transparent',
  },
  frameOverlayImage: { width: '100%', aspectRatio: 4 / 5 },
  frameOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'column',
    justifyContent: 'flex-end',
    alignItems: 'stretch',
    backgroundColor: 'transparent',
    borderTopWidth: 0,
    overflow: 'visible',
    padding: 0,
    margin: 0,
  },
  frameTextBand: {
    backgroundColor: '#FCFCFC',
    paddingTop: 2,
    paddingBottom: 2,
    paddingHorizontal: 10,
    zIndex: 0,
    justifyContent: 'flex-end',
  },
  frameTextBandFullBleed: {
    paddingHorizontal: 10,
  },
  frameTextBandInner: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  framePartySocialStrip: {
    width: '100%',
    zIndex: 3,
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  framePartySocialRow: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 4,
    paddingVertical: 0,
  },
  framePartySocialItem: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  framePartySocialText: {
    marginLeft: 3,
    flexShrink: 1,
  },
  userPhotoActual: {
    width: 135,
    height: 135,
    borderRadius: 0,
    borderWidth: 0,
    margin: 0,
    padding: 0,
    overflow: 'hidden',
    backgroundColor: 'transparent',
  },
  frameAvatarImage: {
    backgroundColor: 'transparent',
  },
  avatarDock: {
    position: 'absolute',
    zIndex: 4,
    width: 135,
    height: 135,
    margin: 0,
    padding: 0,
    justifyContent: 'flex-end',
  },
  avatarDockRight: { right: 0, left: null as unknown as number, alignItems: 'flex-end' },
  avatarDockLeft: { left: 0, right: null as unknown as number, alignItems: 'flex-start' },
  userName: {
    fontSize: 16,
    color: '#0F172A',
    textAlign: 'center',
    marginBottom: 0,
    paddingBottom: 0,
    lineHeight: 18,
  },
  userDesignation: {
    fontSize: 13,
    color: '#64748B',
    textAlign: 'center',
    marginVertical: 0,
    paddingVertical: 0,
    lineHeight: 14,
  },
  userDesignationStacked: { marginTop: 0 },
});
